
spring:
  datasource:
    data-username: antatest
    data-password: anta
    url: jdbc:mysql://localhost:3306/test_anta
  mvc:
    locale: zh_CN
    dispatch-trace-request: true
    date-format: yyyy-MM-dd




mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.abo.model
  configuration:
    map-underscore-to-camel-case: true




